export default {
  LOG_IN: 'LOG_IN',
  LOG_ERROR: 'LOG_ERROR',
  REGISTER_USER: 'REGISTER_USER',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  CREATE_DISCIPLINE: 'CREATE_DISCIPLINE',
  CREATE_NEW_CLASS: 'CREATE_NEW_CLASS',
  DELETE_ONE_CLASS: 'DELETE_ONE_CLASS',
  LOG_OUT_USER: 'LOG_OUT_USER',
};
