import { StyleSheet } from 'react-native';

export default StyleSheet.create({

  container: {

  },
  background_img_dashboart: {
    width: 1028,
    height: 1864,
  },
  background_img_dashboart_imageStyle: {
    opacity: 0.5,
  },

  avatar_circle: {
    top: 690,
    left: 734,
    width: 135,
    height: 135,
    position: 'absolute',
  },
  icon_avatar: {
    top: 5,
    left: 5.5,
    width: 125,
    height: 125,
    borderRadius: 50,
  },
  rect_name: {
    top: 915,
    left: 680,
    width: 250,
    height: 35,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 15,
  },
  name2: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
    marginTop: 5,
    marginLeft: 20,
  },
  yourName: {
    top: 891,
    left: 680,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
  },
  yourSurname: {
    top: 961,
    left: 680,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
  },
  rect_surname: {
    top: 987,
    left: 682,
    width: 250,
    height: 35,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 15,
  },
  surname: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
    marginTop: 5,
    marginLeft: 20,
  },
  discipline: {
    top: 1040,
    left: 682,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
  },
  rect_discipline: {
    top: 1064,
    left: 682,
    width: 250,
    height: 35,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 15,
  },
  discipline2: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
    marginTop: 5,
    marginLeft: 20,
  },
  degree: {
    top: 1116,
    left: 682,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
  },
  rect_degree: {
    top: 1140,
    left: 682,
    width: 250,
    height: 35,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 15,
  },
  degree2: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
    marginTop: 5,
    marginLeft: 20,
  },
  btn_upgrade: {
    top: 1200,
    left: 727,
    width: 168,
    height: 65,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#000000',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 0.35,
    shadowRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  upgrade: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 28,
  },
  btn_camera: {
    top: 800,
    left: 875,
    width: 71,
    height: 47,
    position: 'absolute',
    backgroundColor: 'rgba(230,230, 230,0.84)',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 0.4,
    shadowRadius: 0,
  },
  icon_camera: {
    height: 37,
    width: 32,
  },

  background_img_dashboartStack: {
    marginTop: -636,
    marginLeft: -606,
  },
});
