import { StyleSheet } from 'react-native';

export default StyleSheet.create({

  container: {
    flex: 1,
  },
  background_img_dashboart: {
    width: 1028,
    height: 1864,
    position: 'absolute',
    borderRadius: 15,
    left: 0,
    top: 0,
    overflow: 'hidden',
  },
  background_img_dashboart_imageStyle: {
    opacity: 0.5,
  },
  btn_logout: {
    top: 573,
    left: 410,
    width: 59,
    height: 44,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 0,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  incon_logout: {
    height: 28,
    width: 32,
  },
  tori_icon: {
    width: 39,
    height: 61,
  },
  btn_profile: {
    top: 573,
    left: 145,
    width: 59,
    height: 44,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 0,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title_rectangle: {
    top: 655,
    left: 135,
    width: 350,
    height: 62,
    position: 'absolute',
    backgroundColor: 'rgba(230,230, 230,0)',
    borderWidth: 3,
    borderColor: '#000000',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title_create_new_class: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 30,
    fontWeight: 'bold',
  },

  form_new_class: {
    top: 730,
    left: 140,
    flex: 1,
    maxHeight: 450,
    width: 340,
    justifyContent: 'center',
  },

  day_title: {
    top: 40,
    left: 30,
    position: 'absolute',
    fontFamily: 'arial',
    fontWeight: 'bold',
    color: '#121212',
    fontSize: 25,
  },
  rect_day: {
    top: 80,
    left: 25,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  input_day: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },

  hour_title: {
    top: 60,
    left: 5,
    position: 'absolute',
    fontFamily: 'arial',
    fontWeight: 'bold',
    color: '#121212',
    fontSize: 25,
  },
  rect_hour: {
    top: 100,
    left: 50,
    width: 200,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  input_hour: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },

  discipline_title: {
    top: 245,
    left: 30,
    position: 'absolute',
    fontFamily: 'arial',
    fontWeight: 'bold',
    color: '#121212',
    fontSize: 25,
  },
  rect_discipline: {
    top: 285,
    left: 25,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  input_discipline: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },

  button_confirm: {
    top: 460,
    left: 45,
    width: 260,
    height: 65,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#000000',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.35,
    shadowRadius: 0,
  },
  confirmBtn: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 28,
    textAlign: 'center',
    marginTop: 13,
  },

  background_img_dashboartStack: {
    width: 1028,
    height: 1864,
    marginTop: -556,
    marginLeft: -115,
  },
});
