import { StyleSheet } from 'react-native';

export default StyleSheet.create({

  container: {
    flex: 1,
  },
  background_img_dashboart: {
    width: 1028,
    height: 1864,
    position: 'absolute',
    borderRadius: 15,
    left: 0,
    top: 0,
    overflow: 'hidden',
  },
  background_img_dashboart_imageStyle: {
    opacity: 0.5,
  },
  btn_logout: {
    top: 573,
    left: 410,
    width: 59,
    height: 44,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 0,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  incon_logout: {
    height: 28,
    width: 32,
  },
  tori_icon: {
    width: 39,
    height: 61,
  },
  btn_profile: {
    top: 573,
    left: 145,
    width: 59,
    height: 44,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 0,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title_rectangle: {
    top: 655,
    left: 219,
    width: 186,
    height: 62,
    position: 'absolute',
    backgroundColor: 'rgba(230,230, 230,0)',
    borderWidth: 3,
    borderColor: '#000000',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title_classes: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 30,
    fontWeight: 'bold',
  },

  btn_new_class: {
    top: 10,
    left: 210,
    width: 47,
    height: 47,
    position: 'absolute',
    backgroundColor: 'rgba(230,230, 230,0.84)',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 0,
  },
  icon_plus: {
    height: 40,
    width: 40,
  },
  background_img_dashboartStack: {
    width: 1028,
    height: 1864,
    marginTop: -556,
    marginLeft: -115,
  },
});
