import { StyleSheet } from 'react-native';

export default StyleSheet.create({

  container: {
    flex: 1,
  },
  image1: {
    top: -100,
    left: 0,
    width: 933,
    height: 819,
    position: 'absolute',
  },
  image1_imageStyle: {
    opacity: 0.55,
  },
  titleimage: {
    width: 350,
    height: 50,
    top: 150,
    left: 265,
  },
  button_confirm: {
    top: 650,
    left: 370,
    width: 135,
    height: 65,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#000000',
    shadowColor: 'rgba(0,0,0,1)',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    elevation: 5,
    shadowOpacity: 0.35,
    shadowRadius: 0,
  },
  confirmBtn: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 28,
    textAlign: 'center',
    marginTop: 13,
  },
  rect_email: {
    top: 389,
    left: 257,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  rect_name: {
    top: 292,
    left: 257,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  user_name_title: {
    top: 250,
    left: 276,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
  },
  input_user_name: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },
  password_title: {
    top: 452,
    left: 276,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
  },
  input_email: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },
  confirm_password_title: {
    top: 500,
    left: 276,
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
  },
  rect_password: {
    top: 489,
    left: 257,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  input_password: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
    marginTop: 7,
    marginLeft: 19,
  },
  rect_password_two: {
    top: 586,
    left: 257,
    width: 300,
    height: 45,
    position: 'absolute',
    backgroundColor: '#E6E6E6',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 7,
  },
  inputPassword2: {
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 20,
    marginTop: 10,
    marginLeft: 19,
  },
  email_title: {
    top: 354,
    left: 276,
    position: 'absolute',
    fontFamily: 'arial',
    color: '#121212',
    fontSize: 25,
  },
  image_Stack: {
    width: 953,
    height: 761,
    marginLeft: -242,
  },
});
